# Generated by Django 4.2.16 on 2024-12-24 22:17

import apis.models.mixins.uid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='apis.lookup')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('merchant_type', models.CharField(choices=[('internet', 'Internet'), ('water', 'Water'), ('tv', 'TV'), ('gym', 'Gym'), ('garbage', 'Garbage')], max_length=50)),
                ('code', models.PositiveIntegerField(editable=False, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantMember',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Merchant', 'Merchant'), ('Customer', 'Customer')], default='Customer', max_length=50)),
                ('cnic', models.CharField(max_length=13, null=True)),
                ('picture', models.ImageField(null=True, upload_to='protected/picture')),
                ('primary_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Primary Phone')),
                ('code', models.PositiveIntegerField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'MerchantsMembersRegister',
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantMembership',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(null=True)),
                ('secondary_phone', models.CharField(max_length=10, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_memberships', to='apis.lookup')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_memberships', to='apis.lookup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='apis.merchantmember')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to='apis.merchant')),
            ],
            options={
                'unique_together': {('member', 'merchant')},
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.AddField(
            model_name='merchantmember',
            name='memberships',
            field=models.ManyToManyField(related_name='users', through='apis.MerchantMembership', to='apis.merchant'),
        ),
        migrations.AddField(
            model_name='merchantmember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='merchantmember',
            unique_together={('user', 'role', 'cnic', 'primary_phone')},
        ),
    ]
