# Generated by Django 4.2.16 on 2025-01-11 21:29

import apis.models.merchant
import apis.models.mixins.uid
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=15)),
                ('is_monthly', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_user_invoice', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField(default=datetime.datetime(2025, 1, 26, 21, 29, 19, 516257, tzinfo=datetime.timezone.utc))),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('tv', 'TV'), ('gym', 'Gym'), ('milk', 'Milk'), ('water', 'Water'), ('hostel', 'Hostel'), ('madrsa', 'Madrsa'), ('academy', 'Academy'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('landlord', 'Landlord'), ('installment', 'Installment')], max_length=50)),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('commission_structure', models.JSONField(default=apis.models.merchant.get_default_commission_structure, help_text='Stores commission tiers for cash and online transactions. Example: \n            {\n                "cash": [\n                    {"max_credit": 1000, "commission": 1},\n                    {"max_credit": 3000, "commission": 3},\n                    {"max_credit": 5000, "commission": 5}\n                ],\n                "online": [\n                    {"max_credit": 1000, "commission": 2},\n                    {"max_credit": 3000, "commission": 5},\n                    {"max_credit": 5000, "commission": 8}\n                ]\n            }\n        ')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantMember',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cnic', models.CharField(blank=True, max_length=13, null=True)),
                ('picture', models.CharField(blank=True, max_length=1000, null=True)),
                ('primary_phone', models.CharField(max_length=10, unique=True, verbose_name='Primary Phone')),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.merchant')),
            ],
            options={
                'verbose_name': 'MerchantsMembersRegister',
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='MerchantMembership',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(null=True)),
                ('area', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.CharField(blank=True, max_length=1000, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_monthly', models.BooleanField(default=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.CharField(editable=False, max_length=6, unique=True)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='apis.merchantmember')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apis.merchant')),
            ],
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_commission_paid', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=None, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('type', models.CharField(choices=[('commission', 'Commission'), ('billing', 'Billing')], default='billing', max_length=20)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='credit', max_length=15)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_invoices', to='apis.invoice')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_transactions', to='apis.merchant')),
                ('merchant_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_transactions', to='apis.merchantmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='SupplyRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given', models.SmallIntegerField(default=0)),
                ('taken', models.SmallIntegerField(default=0)),
                ('merchant_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_records', to='apis.merchantmembership')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.AddField(
            model_name='merchantmember',
            name='merchant_memberships',
            field=models.ManyToManyField(related_name='customer_memberships', through='apis.MerchantMembership', to='apis.merchant'),
        ),
        migrations.AddField(
            model_name='merchantmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Merchant', 'Merchant'), ('Customer', 'Customer')], max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apis.merchantmember')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='apis.lookup')),
            ],
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
        migrations.AddIndex(
            model_name='merchantmembership',
            index=models.Index(fields=['member', 'merchant', 'is_active'], name='apis_mercha_member__bba451_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantmembership',
            unique_together={('member', 'merchant')},
        ),
        migrations.AlterUniqueTogether(
            name='merchantmember',
            unique_together={('user', 'cnic', 'primary_phone')},
        ),
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together={('name', 'type')},
        ),
    ]
