# Generated by Django 4.2.16 on 2025-01-15 12:44

import apis.models.mixins.uid
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 12, 44, 3, 479941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='apis.merchantmember')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apis.models.mixins.uid.UIDMixin),
        ),
    ]
