# Generated by Django 4.2.16 on 2025-02-21 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantmember',
            options={'permissions': [('add_staff', 'Can add staff'), ('view_staff', 'Can view staff'), ('change_staff', 'Can change staff'), ('add_customers', 'Can add customers'), ('view_customers', 'Can view customers'), ('change_customers', 'Can change customers'), ('view_pdf', 'Can download PDF'), ('view_excel', 'Can download Excel'), ('view_dashboard', 'Can view dashboard')], 'verbose_name': 'Members Register'},
        ),
        migrations.AddField(
            model_name='merchantmember',
            name='push_notification_id',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 8)),
        ),
    ]
