# Generated by Django 4.2.16 on 2025-01-20 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_invoice_due_date_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='apis.merchantmember'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 12, 44, 42, 922324, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='handled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_invoices', to='apis.merchantmember'),
        ),
        migrations.AlterField(
            model_name='merchantmember',
            name='picture',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='merchantmembership',
            name='picture',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
