# Generated by Django 4.2.16 on 2025-02-28 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_merchantmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='merchant',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 15)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=15),
        ),
    ]
