# Generated by Django 4.2.16 on 2025-03-02 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_transactionhistory_options_merchant_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='debit',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 17)),
        ),
    ]
