# Generated by Django 4.2.16 on 2025-03-12 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_transactionhistory_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='apis.merchantmembership'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 27)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancel', 'Cancel')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('other', 'Other'), ('monthly', 'Monthly'), ('one_time', 'One Time'), ('miscellaneous', 'Miscellaneous')], default='monthly', max_length=15),
        ),
    ]
