# Generated by Django 4.2.16 on 2025-01-29 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_amount_due_invoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 10, 40, 36, 31851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='merchantmember',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='apis.merchant'),
        ),
    ]
