# Generated by Django 4.2.16 on 2025-01-29 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_invoice_due_date_alter_merchantmember_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmembership',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 11, 36, 18, 343242, tzinfo=datetime.timezone.utc)),
        ),
    ]
